version: '3'
services:
  nest:
    build: ./docker
    entrypoint: ./docker/entrypoint.sh
    container_name: nest
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - postgres

  react:
    build: ./docker/react
    entrypoint: ./docker/entrypoint.sh
    container_name: react
    ports:
      - '5000:5000'
    volumes:
      - ./connect-lab:/home/node/app
    depends_on:
      - db
    networks:
      - postgres

  db:
    build: ./docker/postgres
    container_name: postgres
    restart: always
    tty: true
    ports:
      - '3333:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
